import meraki
import getpass
import csv


def merakiError(e):
    """
    Function to print the error generated by Meraki's SDK during any API call made to via the SDK with a try logic attached.
    Args:
            e (String): Error message generated and formatted by the Meraki SDK.
    """
    print(f"Meraki API error: {e}")


def pythonError(e):
    """
    Function to print the error generated by Python during any API calls made with a try logic attached.
    Args:
            e (String): Python Error message.
    """
    print(f"Python API error: {e}")


def getMerakiOrgs():

    merakiOrgList = []

    try:
        merakiOrgList = dashboard.organizations.getOrganizations()
    except meraki.APIError as e:
        print(merakiError(e))
    except Exception as e:
        print(pythonError(e))

    return merakiOrgList


def getOrgSecEvents(orgId, orgName):
    # The below is some test data as my API call returned zero events
    secEvents = []

    try:
        # Default time span is 31 days but you can add a timespan in seconds up to 365 days.
        secEvents = dashboard.appliance.getOrganizationApplianceSecurityEvents(
            organizationId=orgId, total_pages="all")
    except meraki.APIError as e:
        print(merakiError(e))
    except Exception as e:
        print(pythonError(e))

    # Append org name to each event
    for event in secEvents:
        event["orgName"] = orgName

    return secEvents


if "__main__" == __name__:

    """
    This is what is run when the file is run directly, this will setup the script, get a list of Meraki networks and back each up.
    """

    # Setting up Meraki SDK
    apiKey = getpass.getpass()

    dashboard = meraki.DashboardAPI(api_key=apiKey,
                                    print_console=False,
                                    log_path="",
                                    retry_4xx_error=True)

    # Setting up csv file
    exportFile = "sec_event_export.csv"
    exportFileHeaders = ["orgName", "ts", "eventType", "clientName", "clientMac", "clientIp", "srcIp", "destIp",
                         "protocol", "uri", "canonicalName", "destinationPort", "fileHash", "fileType",
                         "fileSizeBytes", "disposition", "action", "blocked", "ruleId", "priority", "signature",
                         "classification", "sigSource", "message", "deviceMac"]

    # Getting List of Orgs
    merakiOrgList = getMerakiOrgs()

    secEventList = []
    for org in merakiOrgList:
        orgName = org["name"]
        orgId = org["id"]

        sevEvents = getOrgSecEvents(orgId, orgName)
        for event in sevEvents:
            secEventList.append(event)

    with open(exportFile, "w") as csvoutput:
        csvfile = csv.DictWriter(csvoutput, delimiter=",",
                                 fieldnames=exportFileHeaders)
        csvfile.writeheader()

        for event in secEventList:
            csvfile.writerow(event)
